### ISSUE TITLE
Rajouts de Commandes Utilitaires

### ISSUE THREAD

**Issue by ChifuyuKR** [HevelMc/Electryon#39]
Commands :

- [ ] /informations

Description : 
Utilisable pour n'importe quel utilisateur.
Une fois cette commande effectuée, elle permet à l'utilisateur de recevoir un message/afficher une interface  contenant les informations importantes et relatives au serveur

- [x] /staff

Description : 
Donne la liste des membres du staff du serveur

- [x] /liens

Description : 
Utilisable pour n'importe quel utilisateur.
Une fois cette commande effectuée, elle permet à l'utilisateur de recevoir un message contenant les liens important relatifs au serveur (forum, site, discord etc..)

**Comment by HevelMc** [comment]
- [x] /modifygroup
**Description:**
- **Permission:** Utilisable uniquement par les joueurs avec la permission "*" ou les opérateurs serveur.
- **Usage:** Change le grade du joueur cible
- **Forme correcte:** /modifygroup <PSEUDO> add/remove <Groupe>


- [x] /discord
**Description:**
- **Permission:** Aucune
- **Usage:** Donne le lien de notre serveur discord
