### ISSUE TITLE
Finir le systéme de palier + shop de paliers

### ISSUE THREAD

**Issue by ChifuyuKR** [HevelMc/Electryon#50]
- [x] le système de palier (équation d'évolution) @HevelMc 

### manque d'item dans les paliers:

- [ ] 1 - 1 item
- [ ] 2 - 2 items
- [ ] 4 - 2 items
- [ ] 6 - 2 items
- [ ] 7 - 2 items
- [ ] 8 - 1 item
- [ ] 10 - 3 items
- [ ] 11 - ( 1 item...)
- [ ] 12 - 2 items
- [x] 13 - 1 item

Total item: 17

**Comment by Jujua31** [comment]
Temps donné avant la béta fermée | 1 Janvier 2019

**Comment by HevelMc** [comment]
J'ai fini mon coté !

**Comment by HevelMc** [comment]
j'chui pas content c'est pas fini ça.
C'est du travail baclé moi j'dis...

**Comment by HevelMc** [comment]
`Issue ré-ouverte, taches à finir.`

**Comment by HevelMc** [comment]
### marque d'item dans les paliers:

1 - 1 item
2 - 2 items
4 - 2 items
6 - 2 items
7 - 2 items
8 - 1 item
10 - 3 items
11 - ( 1 item...)
12 - 2 items
13 - 1 item

Total item: 17
