### ISSUE TITLE
Systéme de sanctions global 

### ISSUE THREAD

**Issue by JuliannMerit** [HevelMc/Electryon#57]
- [x] Gban
- [x] Gkick
- [x] Gtempban
- [x] Gunban
- [ ] gmute
- [ ] Gban-ip
- [ ] GBan-list

- [ ] Ban
- [ ] TempBan
- [ ] Kick
- [ ] Mute
- [ ] Warn
- [ ] Ban-IP
- [ ] Ban-List

**Comment by Jujua31** [comment]
temps donné: avant la béta fermée (1er janvier)

**Comment by WhiteColors** [comment]
Par rapport au ban, c'est le même effet que le gban ?

**Comment by JuliannMerit** [comment]
Non le ban c'est que sur le serveur sur le quelle le joueur je trouve et je gban c'est sur tout le network
