### ISSUE TITLE
Ulfric !

### ISSUE THREAD

**Issue by HevelMc** [HevelMc/Electryon#69]
- [x] Configurer Ulfric pour donner des explications. @ChifuyuNee 
- [x] Retoucher le formatage @ChifuyuNee 
- [x] Configurer Ulfric pour donner le palier n°1 et le grade Citoyen. @HevelMc

**Comment by HevelMc** [comment]
Mon coté est fait

**Comment by ChifuyuKR** [comment]
Texte réalisé à 75%
