### ISSUE TITLE
Systéme de messages global 

### ISSUE THREAD

**Issue by ChifuyuKR** [HevelMc/Electryon#70]
Contexte : Pour voir envoyer un message privé à une personne du serveur sur un autre serveur 
ex : player1 sur serveur survie envoie un message à player2 sur le serveur UHC

**Comment by HevelMc** [comment]
Commande /msg et /r sont fonctionnelles et intra serveur
Des aliases comme _emsg, message, emessage, whisper, ewhisper, m_ sont également disponibles.
