### ISSUE TITLE
Tp spawn quand on est afk

### ISSUE THREAD

**Issue by JuliannMerit** [HevelMc/Electryon#80]
se faire tp au spawn quand est afk

**Comment by HevelMc** [comment]
Terminé

**Comment by ChifuyuKR** [comment]
Note : Il faudrait 

- [x] Faire une zone afk (pourquoi pas dans le paradis ?)
- [x] les tp autre part
- [x] empêcher les collisions dans le spawn pour éviter de d'unafk le joueur

**Comment by ChifuyuKR** [comment]
Prototype :

command /afk:
	trigger:
		wait 2 tick
		if {value.afk} <= 1:
			add 1 to {value.afk}
			set {afklast.%player%} to player's location
			teleport player to {afk.1}
			send player title "&3Vous êtes désormais AFK." with subtitle "&dBougez pour retourner à votre emplacement précédant." for 999 days
		if {value.afk} >= 2:
			teleport player to {afk.2}
			send player title "&3Vous êtes désormais AFK." with subtitle "&dBougez pour retourner à votre emplacement précédant." for 999 days
		on player movement:
			add -1 to {value.afk}
			teleport player to {afklast.%player%}
			send player title "&3Vous n'êtes plus AFK." with subtitle "&2Bon retour parmis les humains." for 2 seconds

command /setvalueafk:
	permission: afkop
	trigger:
		set {value.afk} to 0
		send "&cvalue afk = 0"

command /setafk [<text>]: 
	permission: afkop
	trigger:
		if arg 1 is not set:
			send "&cErreur, veuillez selectionner un point d'AFK (entre 1 et 2)"
		if arg 1 is "1":
			set {afk.1} to player's location
			send "&a&lSET &bAFK &c1 &7effectué avec succés !"
		if arg 1 is "2":
			set {afk.2} to player's location
			send "&a&lSET &bAFK &c2 &7effectué avec succés !"

command /tpafk [<text>]:
	permission: afkop
	trigger:
		if arg 1 is "1":
			teleport player to {afk.1}
		if arg 1 is "2":
			teleport player to {afk.2}

**Comment by HevelMc** [comment]
Résolu (point de tp  =  spawn du paradis) temporairement en tout cas.
